version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  user:
    build: api-user-challenge/
    container_name: user
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    networks:
      - app-network
  camel-user:
    build: camel-user-challenge/
    container_name: camel-user
    ports:
      - 9090:8080
    environment:
      - SERVER_PORT=8080
      - USERS_URL=http://user:8080
    networks:
      - app-network

  account:
    build: api-account-challenge/
    container_name: account
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8080
      - MQ_HOST=rabbitmq
      - SERVICES_USER_URL=http://user:8080
    networks:
      - app-network
  camel-account:
    build: camel-account-challenge/
    container_name: camel-account
    ports:
      - 9091:8080
    environment:
      - SERVER_PORT=8080
      - ACCOUNTS_URL=http://account:8080
    networks:
      - app-network

  transaction:
    build: api-transactions-challenge/
    container_name: transaction
    ports:
      - "8082:8080"
    environment:
      - SERVER_PORT=8080
      - MQ_HOST=rabbitmq
      - SERVICES_ACCOUNT_URL=http://account:8080
    networks:
      - app-network
  camel-transaction:
    build: camel-transaction-challenge/
    container_name: camel-transaction
    ports:
      - 9092:8080
    environment:
      - SERVER_PORT=8080
      - TRANSACTIONS_URL=http://transaction:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
